package com.sys.exam.service.impl;

import java.util.List;

import com.sys.exam.database.bean.QuestionBase;
import com.sys.exam.service.ManagerService;
import com.sys.exam.service.QuestionBaseService;


/**
 * QuestionBase generated by MyEclipse Persistence Tools
 */

public class QuestionBaseServiceImpl implements QuestionBaseService 
{

    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }

	@Override
	public List<QuestionBase> findQbList() {
		// TODO Auto-generated method stub
		return null;
	}

}