package com.sys.exam.service.impl;

import java.util.List;

import com.sys.exam.database.model.UqType;
import com.sys.exam.service.ManagerService;
import com.sys.exam.service.UserQuestionService;

/**
 * UserQuestion generated by MyEclipse Persistence Tools
 */

public class UserQuestionServiceImpl implements UserQuestionService 
{

    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }

	@Override
	public List<UqType> findUqTypeList(Long ueId) throws Exception {
		// TODO Auto-generated method stub
		return null;
	} 

}