package com.sys.exam.service.impl;

import com.sys.exam.service.UserExamService;


/**
 * UserExam generated by MyEclipse Persistence Tools
 */

public class UserExamServiceImpl implements UserExamService 
{

    
}