package com.sys.exam.service.impl;

import com.sys.exam.service.UserService;


/**
 * User generated by MyEclipse Persistence Tools
 */

public class UserServiceImpl implements UserService 
{

    

}