package com.sys.exam.service.impl;

import com.sys.exam.service.UserQuestionService;

/**
 * UserQuestion generated by MyEclipse Persistence Tools
 */

public class UserQuestionServiceImpl implements UserQuestionService 
{

   

}