package com.sys.exam.service;

import java.util.Set;

import com.sys.exam.database.bean.Options;

/**
 * Options generated by MyEclipse Persistence Tools
 */

public interface OptionsService 
{

    void saveSet(Set<Options> setOptions);

    

}