package com.sys.exam.service;

import com.sys.exam.database.bean.Questions;


/**
 * Questions generated by MyEclipse Persistence Tools
 */

public interface QuestionsService 
{

    void saveQuestion(Questions que);

    

}