package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * ExamQuestion generated by MyEclipse Persistence Tools
 */

public class ExamQuestion implements java.io.Serializable
{

    // Fields

    private long eqId;

    private Exam exam;

    private Questions questions;

    private float eqValue;

    private Set userQuestions = new HashSet(0);

    // Constructors

    /** default constructor */
    public ExamQuestion()
    {
    }

    /** minimal constructor */
    public ExamQuestion(Exam exam, Questions questions, float eqValue)
    {
        this.exam = exam;
        this.questions = questions;
        this.eqValue = eqValue;
    }

    /** full constructor */
    public ExamQuestion(Exam exam, Questions questions, float eqValue,
            Set userQuestions)
    {
        this.exam = exam;
        this.questions = questions;
        this.eqValue = eqValue;
        this.userQuestions = userQuestions;
    }

    // Property accessors

    public long getEqId()
    {
        return this.eqId;
    }

    public void setEqId(long eqId)
    {
        this.eqId = eqId;
    }

    public Exam getExam()
    {
        return this.exam;
    }

    public void setExam(Exam exam)
    {
        this.exam = exam;
    }

    public Questions getQuestions()
    {
        return this.questions;
    }

    public void setQuestions(Questions questions)
    {
        this.questions = questions;
    }

    public float getEqValue()
    {
        return this.eqValue;
    }

    public void setEqValue(float eqValue)
    {
        this.eqValue = eqValue;
    }

    public Set getUserQuestions()
    {
        return this.userQuestions;
    }

    public void setUserQuestions(Set userQuestions)
    {
        this.userQuestions = userQuestions;
    }

}