package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * QuestionCategory generated by MyEclipse Persistence Tools
 */

public class QuestionCategory implements java.io.Serializable
{

    // Fields

    private long qcId;

    private String qcName;

    private float qcRatio;

    private Set questionses = new HashSet(0);

    // Constructors

    /** default constructor */
    public QuestionCategory()
    {
    }

    /** minimal constructor */
    public QuestionCategory(String qcName)
    {
        this.qcName = qcName;
    }

    /** full constructor */
    public QuestionCategory(String qcName, float qcRatio, Set questionses)
    {
        this.qcName = qcName;
        this.qcRatio = qcRatio;
        this.questionses = questionses;
    }

    // Property accessors

    public long getQcId()
    {
        return this.qcId;
    }

    public void setQcId(long qcId)
    {
        this.qcId = qcId;
    }

    public String getQcName()
    {
        return this.qcName;
    }

    public void setQcName(String qcName)
    {
        this.qcName = qcName;
    }

    public float getQcRatio()
    {
        return this.qcRatio;
    }

    public void setQcRatio(float qcRatio)
    {
        this.qcRatio = qcRatio;
    }

    public Set getQuestionses()
    {
        return this.questionses;
    }

    public void setQuestionses(Set questionses)
    {
        this.questionses = questionses;
    }

}