package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by MyEclipse Persistence Tools
 */

public class Questions implements java.io.Serializable
{

    // Fields

    private long quesId;

    private QuestionCategory questionCategory;

    private QuestionBase questionBase;

    private String quesDes;

    private Integer quesType;

    private Integer quesDifficulty;

    private Integer quesAnswer;

    private Set examQuestions = new HashSet(0);

    private Set optionses = new HashSet(0);

    // Constructors

    /** default constructor */
    public Questions()
    {
    }

    /** minimal constructor */
    public Questions(QuestionCategory questionCategory,
            QuestionBase questionBase, String quesDes, Integer quesType,
            Integer quesDifficulty, Integer quesAnswer)
    {
        this.questionCategory = questionCategory;
        this.questionBase = questionBase;
        this.quesDes = quesDes;
        this.quesType = quesType;
        this.quesDifficulty = quesDifficulty;
        this.quesAnswer = quesAnswer;
    }

    /** full constructor */
    public Questions(QuestionCategory questionCategory,
            QuestionBase questionBase, String quesDes, Integer quesType,
            Integer quesDifficulty, Integer quesAnswer, Set examQuestions,
            Set optionses)
    {
        this.questionCategory = questionCategory;
        this.questionBase = questionBase;
        this.quesDes = quesDes;
        this.quesType = quesType;
        this.quesDifficulty = quesDifficulty;
        this.quesAnswer = quesAnswer;
        this.examQuestions = examQuestions;
        this.optionses = optionses;
    }

    // Property accessors

    public long getQuesId()
    {
        return this.quesId;
    }

    public void setQuesId(long quesId)
    {
        this.quesId = quesId;
    }

    public QuestionCategory getQuestionCategory()
    {
        return this.questionCategory;
    }

    public void setQuestionCategory(QuestionCategory questionCategory)
    {
        this.questionCategory = questionCategory;
    }

    public QuestionBase getQuestionBase()
    {
        return this.questionBase;
    }

    public void setQuestionBase(QuestionBase questionBase)
    {
        this.questionBase = questionBase;
    }

    public String getQuesDes()
    {
        return this.quesDes;
    }

    public void setQuesDes(String quesDes)
    {
        this.quesDes = quesDes;
    }

    public Integer getQuesType()
    {
        return this.quesType;
    }

    public void setQuesType(Integer quesType)
    {
        this.quesType = quesType;
    }

    public Integer getQuesDifficulty()
    {
        return this.quesDifficulty;
    }

    public void setQuesDifficulty(Integer quesDifficulty)
    {
        this.quesDifficulty = quesDifficulty;
    }

    public Integer getQuesAnswer()
    {
        return this.quesAnswer;
    }

    public void setQuesAnswer(Integer quesAnswer)
    {
        this.quesAnswer = quesAnswer;
    }

    public Set getExamQuestions()
    {
        return this.examQuestions;
    }

    public void setExamQuestions(Set examQuestions)
    {
        this.examQuestions = examQuestions;
    }

    public Set getOptionses()
    {
        return this.optionses;
    }

    public void setOptionses(Set optionses)
    {
        this.optionses = optionses;
    }

}