package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * QuestionBase generated by MyEclipse Persistence Tools
 */

public class QuestionBase implements java.io.Serializable
{

    // Fields

    private long qbId;

    private String qbName;

    private Set questionses = new HashSet(0);

    // Constructors

    /** default constructor */
    public QuestionBase()
    {
    }

    /** minimal constructor */
    public QuestionBase(String qbName)
    {
        this.qbName = qbName;
    }

    /** full constructor */
    public QuestionBase(String qbName, Set questionses)
    {
        this.qbName = qbName;
        this.questionses = questionses;
    }

    // Property accessors

    public long getQbId()
    {
        return this.qbId;
    }

    public void setQbId(long qbId)
    {
        this.qbId = qbId;
    }

    public String getQbName()
    {
        return this.qbName;
    }

    public void setQbName(String qbName)
    {
        this.qbName = qbName;
    }

    public Set getQuestionses()
    {
        return this.questionses;
    }

    public void setQuestionses(Set questionses)
    {
        this.questionses = questionses;
    }

}