package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * UserGroup generated by MyEclipse Persistence Tools
 */

public class UserGroup implements java.io.Serializable
{

    // Fields

    private long ugId;

    private String ugName;

    private Set userGroupRels = new HashSet(0);

    // Constructors

    /** default constructor */
    public UserGroup()
    {
    }

    /** minimal constructor */
    public UserGroup(String ugName)
    {
        this.ugName = ugName;
    }

    /** full constructor */
    public UserGroup(String ugName, Set userGroupRels)
    {
        this.ugName = ugName;
        this.userGroupRels = userGroupRels;
    }

    // Property accessors

    public long getUgId()
    {
        return this.ugId;
    }

    public void setUgId(long ugId)
    {
        this.ugId = ugId;
    }

    public String getUgName()
    {
        return this.ugName;
    }

    public void setUgName(String ugName)
    {
        this.ugName = ugName;
    }

    public Set getUserGroupRels()
    {
        return this.userGroupRels;
    }

    public void setUserGroupRels(Set userGroupRels)
    {
        this.userGroupRels = userGroupRels;
    }

}