package com.sys.exam.database.bean;

/**
 * UserQuestion generated by MyEclipse Persistence Tools
 */

public class UserQuestion implements java.io.Serializable
{

    // Fields

    private long uqId;

    private ExamQuestion examQuestion;

    private UserExam userExam;

    private Integer uqAnswer;

    private Integer uqSign;

    // Constructors

    /** default constructor */
    public UserQuestion()
    {
    }

    /** minimal constructor */
    public UserQuestion(ExamQuestion examQuestion, UserExam userExam,
            Integer uqSign)
    {
        this.examQuestion = examQuestion;
        this.userExam = userExam;
        this.uqSign = uqSign;
    }

    /** full constructor */
    public UserQuestion(ExamQuestion examQuestion, UserExam userExam,
            Integer uqAnswer, Integer uqSign)
    {
        this.examQuestion = examQuestion;
        this.userExam = userExam;
        this.uqAnswer = uqAnswer;
        this.uqSign = uqSign;
    }

    // Property accessors

    public long getUqId()
    {
        return this.uqId;
    }

    public void setUqId(long uqId)
    {
        this.uqId = uqId;
    }

    public ExamQuestion getExamQuestion()
    {
        return this.examQuestion;
    }

    public void setExamQuestion(ExamQuestion examQuestion)
    {
        this.examQuestion = examQuestion;
    }

    public UserExam getUserExam()
    {
        return this.userExam;
    }

    public void setUserExam(UserExam userExam)
    {
        this.userExam = userExam;
    }

    public Integer getUqAnswer()
    {
        return this.uqAnswer;
    }

    public void setUqAnswer(Integer uqAnswer)
    {
        this.uqAnswer = uqAnswer;
    }

    public Integer getUqSign()
    {
        return this.uqSign;
    }

    public void setUqSign(Integer uqSign)
    {
        this.uqSign = uqSign;
    }

}