package com.sys.exam.service;

import com.sys.exam.database.bean.User;


/**
 * User generated by MyEclipse Persistence Tools
 */

public interface UserService 
{

	/**验证登录用户的用户名密码是否正确
	 * @param loginuser
	 * @return
	 * @throws Exception
	 */
	User verifyUser(User loginuser)throws Exception;

    

}