package com.sys.exam.service;

import com.sys.exam.database.bean.UserExam;


/**
 * UserExam generated by MyEclipse Persistence Tools
 */

public interface UserExamService 
{

    /**
      * 关于方法的描述： 周期性的获得学生试卷表格中进行状态的试卷，
      *  判断试卷开始时间加上考试的时长是否大于当前系统时间，
      *  如果大于自动交卷
      */
    void CheckExamTime();
    
    /**
      * 关于方法的描述：提交用户试卷
      * @param ue 用户试卷实体
      */
    void updateSubUserExam(UserExam ue);
    
    
    /**
      * 关于方法的描述：给用户考试判分，更新用户考试表的分数
      * @param ue 用户考试表的实体
      * @return 
      */
    boolean updateGradeJudging(UserExam ue);

    
}