package com.sys.exam.service;

import com.sys.exam.database.Pager;


/**
 * Exam generated by MyEclipse Persistence Tools
 */

public interface ExamService 
{

	/**分页查找考试列表
	 * @param pager 分页信息
	 * @return
	 * @throws Exception
	 */
	Pager findExamList(Pager pager)throws Exception;

   

}