package com.sys.exam.service;

import java.util.List;

import com.sys.exam.database.bean.QuestionCategory;


/**
 * QuestionCategory generated by MyEclipse Persistence Tools
 */

public interface QuestionCategoryService 
{

    void saveOne(QuestionCategory qcnew);

	List<QuestionCategory> findQcList();

   

}