package com.sys.exam.service;

import com.sys.exam.database.bean.QuestionCategory;


/**
 * QuestionCategory generated by MyEclipse Persistence Tools
 */

public interface QuestionCategoryService 
{

    void saveOne(QuestionCategory qcnew);

   

}