package com.sys.exam.service;

import java.util.List;

import com.sys.exam.database.bean.QuestionBase;


/**
 * QuestionBase generated by MyEclipse Persistence Tools
 */

public interface QuestionBaseService 
{

	List<QuestionBase> findQbList();

   

}