package com.sys.exam.service;

import java.util.List;

import com.sys.exam.database.bean.UserGroup;


/**
 * UserGroup generated by MyEclipse Persistence Tools
 */

public interface UserGroupService 
{

	/**查找用户组列表
	 * @return
	 * @throws Exception
	 */
	List<UserGroup> findUgList()throws Exception;


}