package com.sys.exam.service;

import java.util.List;

import com.sys.exam.database.model.UqType;

/**
 * UserQuestion generated by MyEclipse Persistence Tools
 */

public interface UserQuestionService 
{

	/**查找指定的用户考试中的所有题目类型的试题
	 * @param ueId 用户考试id
	 * @return 
	 * @throws Exception
	 */
	List<UqType> findUqTypeList(Long ueId)throws Exception;

   

}