package com.sys.exam.service;

import java.util.List;

import com.sys.exam.database.Pager;
import com.sys.exam.database.bean.User;
import com.sys.exam.database.bean.UserExam;


/**
 * UserExam generated by MyEclipse Persistence Tools
 */

public interface UserExamService 
{

    /**
      * 关于方法的描述： 周期性的获得学生试卷表格中进行状态的试卷，
      *  判断试卷开始时间加上考试的时长是否大于当前系统时间，
      *  如果大于自动交卷
      */
    void updateCheckExamTime();
    
    /**
      * 关于方法的描述：提交用户试卷
      * @param ue 用户试卷实体
      */
    void updateSubUserExam(UserExam ue);
    
    
    /**
      * 关于方法的描述：给用户考试判分，更新用户考试表的分数
      * @param ue 用户考试表的实体
      * @return 
      */
    boolean updateGradeJudging(UserExam ue);

	/**给指定考试导入用户组
	 * @param examId 考试id
	 * @param userGroupId 用户组id
	 * @return null:成功，其他为失败信息
	 * @throws Exception
	 */
	String addUserExam(Long examId, Long userGroupId)throws Exception;

    /**
      * 关于方法的描述：根据用户获得可用的考试列表
      * @param user  用户实体
      * @return 用户考试列表
      */
    List<UserExam> getAvaiExam(User user);

	/**分页查找指定考试的用户信息、状态、成绩等
	 * @param examId 考试id
	 * @param pager 分页信息
	 * @return
	 * @throws Exception
	 */
	Pager findUserScoreList(Long examId, Pager pager)throws Exception;

	/**查找指定id的用户考试
	 * @param ueId 用户考试
	 * @return
	 * @throws Exception
	 */
	UserExam findUeById(Long ueId)throws Exception;

	/**输入用户考试成绩
	 * @param ueId 用户考试id
	 * @param ueGrade 成绩
	 * @return null:成功，其他为错误信息
	 * @throws Exception
	 */
	String updateUeGrade(Long ueId, Float ueGrade)throws Exception;

	/**修改选中用户考试的状态为指定状态
	 * @param ueIdList 选中的用户考试
	 * @param ueState 状态
	 * @return null：成功，其他为错误信息
	 * @throws Exception
	 */
	String updateUesState(List<Long> ueIdList, int ueState)throws Exception;

    
}