package com.sys.exam.database.bean;

/**
 * ExamCateRatio generated by MyEclipse Persistence Tools
 */

public class ExamCateRatio implements java.io.Serializable
{

    // Fields

    private long ecrId;

    private QuestionCategory questionCategory;

    private Exam exam;

    private float ecrRatio;

    // Constructors

    /** default constructor */
    public ExamCateRatio()
    {
    }

    /** full constructor */
    public ExamCateRatio(QuestionCategory questionCategory, Exam exam,
            float ecrRatio)
    {
        this.questionCategory = questionCategory;
        this.exam = exam;
        this.ecrRatio = ecrRatio;
    }

    // Property accessors

    public long getEcrId()
    {
        return this.ecrId;
    }

    public void setEcrId(long ecrId)
    {
        this.ecrId = ecrId;
    }

    public QuestionCategory getQuestionCategory()
    {
        return this.questionCategory;
    }

    public void setQuestionCategory(QuestionCategory questionCategory)
    {
        this.questionCategory = questionCategory;
    }

    public Exam getExam()
    {
        return this.exam;
    }

    public void setExam(Exam exam)
    {
        this.exam = exam;
    }

    public float getEcrRatio()
    {
        return this.ecrRatio;
    }

    public void setEcrRatio(float ecrRatio)
    {
        this.ecrRatio = ecrRatio;
    }

}