package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by MyEclipse Persistence Tools
 */

public class Exam implements java.io.Serializable
{

    // Fields

    private long examId;

    private String examName;

    private Integer examTime;

    private String examCreateTime;

    private Set examQuestions = new HashSet(0);

    private Set userExams = new HashSet(0);

    // Constructors

    /** default constructor */
    public Exam()
    {
    }

    /** minimal constructor */
    public Exam(String examName, Integer examTime, String examCreateTime)
    {
        this.examName = examName;
        this.examTime = examTime;
        this.examCreateTime = examCreateTime;
    }

    /** full constructor */
    public Exam(String examName, Integer examTime, String examCreateTime,
            Set examQuestions, Set userExams)
    {
        this.examName = examName;
        this.examTime = examTime;
        this.examCreateTime = examCreateTime;
        this.examQuestions = examQuestions;
        this.userExams = userExams;
    }

    // Property accessors

    public long getExamId()
    {
        return this.examId;
    }

    public void setExamId(long examId)
    {
        this.examId = examId;
    }

    public String getExamName()
    {
        return this.examName;
    }

    public void setExamName(String examName)
    {
        this.examName = examName;
    }

    public Integer getExamTime()
    {
        return this.examTime;
    }

    public void setExamTime(Integer examTime)
    {
        this.examTime = examTime;
    }

    public String getExamCreateTime()
    {
        return this.examCreateTime;
    }

    public void setExamCreateTime(String examCreateTime)
    {
        this.examCreateTime = examCreateTime;
    }

    public Set getExamQuestions()
    {
        return this.examQuestions;
    }

    public void setExamQuestions(Set examQuestions)
    {
        this.examQuestions = examQuestions;
    }

    public Set getUserExams()
    {
        return this.userExams;
    }

    public void setUserExams(Set userExams)
    {
        this.userExams = userExams;
    }

}