package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by MyEclipse Persistence Tools
 */

public class Exam implements java.io.Serializable
{

    // Fields

    private long examId;

    private String examName;

    private Integer examTime;

    private String examCreateTime;

    private Set examQuesTypes = new HashSet(0);

    private Set userExams = new HashSet(0);

    private Set examCateRatios = new HashSet(0);

    // Constructors

    /** default constructor */
    public Exam()
    {
    }

    /** minimal constructor */
    public Exam(String examName, Integer examTime, String examCreateTime)
    {
        this.examName = examName;
        this.examTime = examTime;
        this.examCreateTime = examCreateTime;
    }

    /** full constructor */
    public Exam(String examName, Integer examTime, String examCreateTime,
            Set examQuesTypes, Set userExams, Set examCateRatios)
    {
        this.examName = examName;
        this.examTime = examTime;
        this.examCreateTime = examCreateTime;
        this.examQuesTypes = examQuesTypes;
        this.userExams = userExams;
        this.examCateRatios = examCateRatios;
    }

    // Property accessors

    public long getExamId()
    {
        return this.examId;
    }

    public void setExamId(long examId)
    {
        this.examId = examId;
    }

    public String getExamName()
    {
        return this.examName;
    }

    public void setExamName(String examName)
    {
        this.examName = examName;
    }

    public Integer getExamTime()
    {
        return this.examTime;
    }

    public void setExamTime(Integer examTime)
    {
        this.examTime = examTime;
    }

    public String getExamCreateTime()
    {
        return this.examCreateTime;
    }

    public void setExamCreateTime(String examCreateTime)
    {
        this.examCreateTime = examCreateTime;
    }

    public Set getExamQuesTypes()
    {
        return this.examQuesTypes;
    }

    public void setExamQuesTypes(Set examQuesTypes)
    {
        this.examQuesTypes = examQuesTypes;
    }

    public Set getUserExams()
    {
        return this.userExams;
    }

    public void setUserExams(Set userExams)
    {
        this.userExams = userExams;
    }

    public Set getExamCateRatios()
    {
        return this.examCateRatios;
    }

    public void setExamCateRatios(Set examCateRatios)
    {
        this.examCateRatios = examCateRatios;
    }

}