package com.sys.exam.database.bean;

/**
 * ExamQuesType generated by MyEclipse Persistence Tools
 */

public class ExamQuesType implements java.io.Serializable
{

    // Fields

    private long eqtId;

    private QuestionType questionType;

    private Exam exam;

    private float eqtValue;

    private Integer eqtNum;

    // Constructors

    /** default constructor */
    public ExamQuesType()
    {
    }

    /** full constructor */
    public ExamQuesType(QuestionType questionType, Exam exam, float eqtValue,
            Integer eqtNum)
    {
        this.questionType = questionType;
        this.exam = exam;
        this.eqtValue = eqtValue;
        this.eqtNum = eqtNum;
    }

    // Property accessors

    public long getEqtId()
    {
        return this.eqtId;
    }

    public void setEqtId(long eqtId)
    {
        this.eqtId = eqtId;
    }

    public QuestionType getQuestionType()
    {
        return this.questionType;
    }

    public void setQuestionType(QuestionType questionType)
    {
        this.questionType = questionType;
    }

    public Exam getExam()
    {
        return this.exam;
    }

    public void setExam(Exam exam)
    {
        this.exam = exam;
    }

    public float getEqtValue()
    {
        return this.eqtValue;
    }

    public void setEqtValue(float eqtValue)
    {
        this.eqtValue = eqtValue;
    }

    public Integer getEqtNum()
    {
        return this.eqtNum;
    }

    public void setEqtNum(Integer eqtNum)
    {
        this.eqtNum = eqtNum;
    }

}