package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by MyEclipse Persistence Tools
 */

public class Questions implements java.io.Serializable
{

    // Fields

    private long quesId;

    private QuestionCategory questionCategory;

    private QuestionType questionType;

    private QuestionBase questionBase;

    private String quesDes;

    private Integer quesDifficulty;

    private Integer quesAnswer;

    private Set optionses = new HashSet(0);

    // Constructors

    /** default constructor */
    public Questions()
    {
    }

    /** minimal constructor */
    public Questions(QuestionCategory questionCategory,
            QuestionBase questionBase, String quesDes, Integer quesDifficulty,
            Integer quesAnswer)
    {
        this.questionCategory = questionCategory;
        this.questionBase = questionBase;
        this.quesDes = quesDes;
        this.quesDifficulty = quesDifficulty;
        this.quesAnswer = quesAnswer;
    }

    /** full constructor */
    public Questions(QuestionCategory questionCategory,
            QuestionType questionType, QuestionBase questionBase,
            String quesDes, Integer quesDifficulty, Integer quesAnswer,
            Set optionses)
    {
        this.questionCategory = questionCategory;
        this.questionType = questionType;
        this.questionBase = questionBase;
        this.quesDes = quesDes;
        this.quesDifficulty = quesDifficulty;
        this.quesAnswer = quesAnswer;
        this.optionses = optionses;
    }

    // Property accessors

    public long getQuesId()
    {
        return this.quesId;
    }

    public void setQuesId(long quesId)
    {
        this.quesId = quesId;
    }

    public QuestionCategory getQuestionCategory()
    {
        return this.questionCategory;
    }

    public void setQuestionCategory(QuestionCategory questionCategory)
    {
        this.questionCategory = questionCategory;
    }

    public QuestionType getQuestionType()
    {
        return this.questionType;
    }

    public void setQuestionType(QuestionType questionType)
    {
        this.questionType = questionType;
    }

    public QuestionBase getQuestionBase()
    {
        return this.questionBase;
    }

    public void setQuestionBase(QuestionBase questionBase)
    {
        this.questionBase = questionBase;
    }

    public String getQuesDes()
    {
        return this.quesDes;
    }

    public void setQuesDes(String quesDes)
    {
        this.quesDes = quesDes;
    }

    public Integer getQuesDifficulty()
    {
        return this.quesDifficulty;
    }

    public void setQuesDifficulty(Integer quesDifficulty)
    {
        this.quesDifficulty = quesDifficulty;
    }

    public Integer getQuesAnswer()
    {
        return this.quesAnswer;
    }

    public void setQuesAnswer(Integer quesAnswer)
    {
        this.quesAnswer = quesAnswer;
    }

    public Set getOptionses()
    {
        return this.optionses;
    }

    public void setOptionses(Set optionses)
    {
        this.optionses = optionses;
    }

}