package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * QuestionType generated by MyEclipse Persistence Tools
 */

public class QuestionType implements java.io.Serializable
{

    // Fields

    private Integer qtId;

    private String qtDes;

    private Set examQuesTypes = new HashSet(0);

    private Set questionses = new HashSet(0);

    // Constructors

    /** default constructor */
    public QuestionType()
    {
    }

    /** minimal constructor */
    public QuestionType(String qtDes)
    {
        this.qtDes = qtDes;
    }

    /** full constructor */
    public QuestionType(String qtDes, Set examQuesTypes, Set questionses)
    {
        this.qtDes = qtDes;
        this.examQuesTypes = examQuesTypes;
        this.questionses = questionses;
    }

    // Property accessors

    public Integer getQtId()
    {
        return this.qtId;
    }

    public void setQtId(Integer qtId)
    {
        this.qtId = qtId;
    }

    public String getQtDes()
    {
        return this.qtDes;
    }

    public void setQtDes(String qtDes)
    {
        this.qtDes = qtDes;
    }

    public Set getExamQuesTypes()
    {
        return this.examQuesTypes;
    }

    public void setExamQuesTypes(Set examQuesTypes)
    {
        this.examQuesTypes = examQuesTypes;
    }

    public Set getQuestionses()
    {
        return this.questionses;
    }

    public void setQuestionses(Set questionses)
    {
        this.questionses = questionses;
    }

}