package com.sys.exam.database.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * UserExam generated by MyEclipse Persistence Tools
 */

public class UserExam implements java.io.Serializable
{

    // Fields

    private long ueId;

    private User user;

    private Exam exam;

    private float ueGrade;

    private Integer ueState;

    private String ueStartTime;

    private String ueEndTime;

    private Set userQuestions = new HashSet(0);

    // Constructors

    /** default constructor */
    public UserExam()
    {
    }

    /** minimal constructor */
    public UserExam(User user, Exam exam, Integer ueState)
    {
        this.user = user;
        this.exam = exam;
        this.ueState = ueState;
    }

    /** full constructor */
    public UserExam(User user, Exam exam, float ueGrade, Integer ueState,
            String ueStartTime, String ueEndTime, Set userQuestions)
    {
        this.user = user;
        this.exam = exam;
        this.ueGrade = ueGrade;
        this.ueState = ueState;
        this.ueStartTime = ueStartTime;
        this.ueEndTime = ueEndTime;
        this.userQuestions = userQuestions;
    }

    // Property accessors

    public long getUeId()
    {
        return this.ueId;
    }

    public void setUeId(long ueId)
    {
        this.ueId = ueId;
    }

    public User getUser()
    {
        return this.user;
    }

    public void setUser(User user)
    {
        this.user = user;
    }

    public Exam getExam()
    {
        return this.exam;
    }

    public void setExam(Exam exam)
    {
        this.exam = exam;
    }

    public float getUeGrade()
    {
        return this.ueGrade;
    }

    public void setUeGrade(float ueGrade)
    {
        this.ueGrade = ueGrade;
    }

    public Integer getUeState()
    {
        return this.ueState;
    }

    public void setUeState(Integer ueState)
    {
        this.ueState = ueState;
    }

    public String getUeStartTime()
    {
        return this.ueStartTime;
    }

    public void setUeStartTime(String ueStartTime)
    {
        this.ueStartTime = ueStartTime;
    }

    public String getUeEndTime()
    {
        return this.ueEndTime;
    }

    public void setUeEndTime(String ueEndTime)
    {
        this.ueEndTime = ueEndTime;
    }

    public Set getUserQuestions()
    {
        return this.userQuestions;
    }

    public void setUserQuestions(Set userQuestions)
    {
        this.userQuestions = userQuestions;
    }

}