package com.sys.exam.service.impl;

import java.util.List;

import com.sys.exam.database.Pager;
import com.sys.exam.service.ExamService;
import com.sys.exam.service.ManagerService;


/**
 * Exam generated by MyEclipse Persistence Tools
 */

public class ExamServiceImpl implements ExamService 
{
    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }

	@Override
	public Pager findExamList(Pager pager) throws Exception {
		StringBuilder hsql=new StringBuilder();
		hsql.append("from Exam exam");
		Pager p=managerService.getExamDao().getPager(hsql.toString(), pager.getCurrentPage(), pager.getPageSize());
		return p;
	}
   

}