package com.sys.exam.service.impl;

import com.sys.exam.service.ExamService;


/**
 * Exam generated by MyEclipse Persistence Tools
 */

public class ExamServiceImpl implements ExamService 
{

   

}