package com.sys.exam.service.impl;

import com.sys.exam.service.ExamQuestionService;


/**
 * ExamQuestion generated by MyEclipse Persistence Tools
 */

public class ExamQuestionServiceImpl implements ExamQuestionService
{

    

}