package com.sys.exam.service.impl;

import com.sys.exam.service.OptionsService;

/**
 * Options generated by MyEclipse Persistence Tools
 */

public class OptionsServiceImpl implements OptionsService 
{

    

}