package com.sys.exam.service.impl;

import com.sys.exam.service.QuestionCategoryService;


/**
 * QuestionCategory generated by MyEclipse Persistence Tools
 */

public class QuestionCategoryServiceImpl implements QuestionCategoryService 
{

   

}