package com.sys.exam.service.impl;

import com.sys.exam.service.QuestionBaseService;


/**
 * QuestionBase generated by MyEclipse Persistence Tools
 */

public class QuestionBaseServiceImpl implements QuestionBaseService 
{

   

}