package com.sys.exam.service.impl;

import com.sys.exam.service.QuestionsService;


/**
 * Questions generated by MyEclipse Persistence Tools
 */

public class QuestionsServiceImpl implements QuestionsService 
{

    

}