package com.sys.exam.service.impl;

import java.util.List;

import com.sys.exam.database.bean.QuestionCategory;
import com.sys.exam.service.ManagerService;
import com.sys.exam.service.QuestionCategoryService;


/**
 * QuestionCategory generated by MyEclipse Persistence Tools
 */

public class QuestionCategoryServiceImpl implements QuestionCategoryService 
{

   
    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }
    
    @Override
    public void saveOne(QuestionCategory qcnew)
    {
       if (null!=qcnew)
    {
        managerService.getQuestionCategoryDao().save(qcnew);
    }//end if
        
    }

	@Override
	public List<QuestionCategory> findQcList() {
		// TODO Auto-generated method stub
		return null;
	}
}