package com.sys.exam.service.impl;

import com.sys.exam.database.bean.QuestionBase;
import com.sys.exam.database.bean.QuestionCategory;
import com.sys.exam.database.bean.Questions;
import com.sys.exam.service.ManagerService;
import com.sys.exam.service.QuestionsService;
import com.sys.exam.util.DocTool;


/**
 * Questions generated by MyEclipse Persistence Tools
 */

public class QuestionsServiceImpl implements QuestionsService 
{

    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }
    
    @Override
    public void saveQuestion(Questions que)
    {
        managerService.getQuestionsDao().save(que);
        
    }

	@Override
	public String addQue(String storeFileName, String qcNam,long qbId) throws Exception {
		String ret=null;
		DocTool docTool=new DocTool(qbId,qcNam);
		docTool.analyseQuestionbase(storeFileName);
		return ret;
	}

}