package com.sys.exam.service.impl;

import com.sys.exam.service.UserGroupService;


/**
 * UserGroup generated by MyEclipse Persistence Tools
 */

public class UserGroupServiceImpl implements UserGroupService 
{


}