package com.sys.exam.service.impl;

import java.util.ArrayList;
import java.util.List;

import com.sys.exam.database.bean.Options;
import com.sys.exam.database.bean.Questions;
import com.sys.exam.database.bean.UserExam;
import com.sys.exam.database.bean.UserQuestion;
import com.sys.exam.database.model.UqModel;
import com.sys.exam.database.model.UqType;
import com.sys.exam.service.ManagerService;
import com.sys.exam.service.UserQuestionService;
import com.sys.exam.util.Constant;

/**
 * UserQuestion generated by MyEclipse Persistence Tools
 */

public class UserQuestionServiceImpl implements UserQuestionService
{

    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }

    @Override
    public List<UqType> findUqTypeList(Long ueId) throws Exception
    {
        String sql = "from UserQuestion uq where uq.userExam.ueId=" + ueId;
        List<UserQuestion> listuqs = managerService.getUserQuestionDao().find(
                sql);
        List<UqType> listUqTypes = new ArrayList<UqType>();

        sql = "from Options order by questions.quesId ,optionOrder";
        List<Options> listOptions = managerService.getOptionsDao().find(sql);

        UqType ut = null;

        for (int i = 1; i <= 3; i++)
        {
            ut = new UqType();
            ut.setType(Constant.QUESTION_SINGLE);
            List<UqModel> listUqms = new ArrayList<UqModel>();
            UqModel uqm = null;
            for (UserQuestion uq : listuqs)
            {
                Questions que = uq.getExamQuestion().getQuestions();
                ut.setTypeScore(uq.getExamQuestion().getEqValue());
                if (que.getQuesType() == i)
                {
                    uqm = new UqModel();
                    uqm.setUq(uq);
                    List<Options> listops = new ArrayList<Options>();
                    for (Options options : listOptions)
                    {
                        if (options.getQuestions().getQuesId() == que
                                .getQuesId())
                        {
                            listops.add(options);
                        }// end if
                    }
                    uqm.setOpList(listops);
                    listUqms.add(uqm);
                }// end if

            }
            ut.setUqModelList(listUqms);
            ut.setUqNum(listUqms.size());
            listUqTypes.add(ut);
        }// end for

        UserExam userex=managerService.getUserExamDao().get(ueId);
        userex.setUeState(Constant.EXAM_STATE_GOING);
        managerService.getUserExamDao().save(userex);
        return listUqTypes;
    }

}