package com.sys.exam.service.impl;

import java.util.Set;

import com.sys.exam.database.bean.Options;
import com.sys.exam.service.ManagerService;
import com.sys.exam.service.OptionsService;

/**
 * Options generated by MyEclipse Persistence Tools
 */

public class OptionsServiceImpl implements OptionsService 
{

    private ManagerService managerService;

    /**
     * @return Returns the managerService.
     */
    public ManagerService getManagerService()
    {
        return managerService;
    }

    /**
     * @param managerService The managerService to set.
     */
    public void setManagerService(ManagerService managerService)
    {
        this.managerService = managerService;
    }
    
    @Override
    public void saveSet(Set<Options> setOptions)
    {
        managerService.getOptionsDao().saveOrUpdateAll(setOptions);
        
    }

}